# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RequetetAttributaire
                                 A QGIS plugin
 This is mu pluggin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-09
        copyright            : (C) 2021 by AMINA
        email                : Amina@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RequetetAttributaire class from file RequetetAttributaire.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MyReqAtt import RequetetAttributaire
    return RequetetAttributaire(iface)
