# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RequetetAttributaire
                                 A QGIS plugin
 This is mu pluggin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-06-09
        git sha              : $Format:%H$
        copyright            : (C) 2021 by AMINA
        email                : Amina@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

from qgis.core import QgsProject

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .MyReqAtt_dialog import RequetetAttributaireDialog
import os.path


class RequetetAttributaire:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'RequetetAttributaire_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&MyReqAtt')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('RequetetAttributaire', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/MyReqAtt/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u''),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def getLayerByName(self,name):
        return QgsProject.instance().mapLayersByName(name)[0]
    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&MyReqAtt'),
                action)
            self.iface.removeToolBarIcon(action)

    def getFeaturesByName(self):
        SelectedLayer=self.getLayerByName(self.dlg.comboBox.currentText())
        Features=[field.name() for field in SelectedLayer.fields()]
        self.dlg.comboBox_2.clear()
        self.dlg.comboBox_2.addItems(Features)

    def setEditText(self):
        self.dlg.EditText.clear()
        self.dlg.EditText.setText(self.dlg.comboBox_2.currentText())
    
    def WriteFromRadio(self,Button):
        self.dlg.EditText.clear()
        self.dlg.EditText.setText(self.dlg.comboBox_2.currentText()+Button.text())

    def runCode(self):
        Request=self.dlg.EditText.text()
        layer=self.getLayerByName(self.dlg.comboBox.currentText())
        layer.selectByExpression(Request)

    def run(self):
        """Run method that performs all the real work"""
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = RequetetAttributaireDialog()
         

        # Fetch the currently loaded layers
        layers = QgsProject.instance().layerTreeRoot().children()
        # Clear the contents of the comboBox from previous runs
        self.dlg.comboBox.clear()
        # Populate the comboBox with names of all the loaded layers
        self.dlg.comboBox.addItems([layer.name() for layer in layers])
        

        #Get Features of the selected layer
        self.dlg.comboBox_2.clear()
        self.getFeaturesByName()
        

        #Listen to Layers Change

        self.dlg.comboBox.currentTextChanged.connect(self.getFeaturesByName)

        # Write the Attribute on EditText
        self.setEditText()
        
        #Listen to Features Change
        self.dlg.comboBox_2.currentTextChanged.connect(self.setEditText)

        #RadioButtons Write Text
        self.dlg.R1.toggled.connect(lambda:self.WriteFromRadio(self.dlg.R1))
        self.dlg.R2.toggled.connect(lambda:self.WriteFromRadio(self.dlg.R2))
        self.dlg.R3.toggled.connect(lambda:self.WriteFromRadio(self.dlg.R3))
        self.dlg.R4.toggled.connect(lambda:self.WriteFromRadio(self.dlg.R4))
        self.dlg.R5.toggled.connect(lambda:self.WriteFromRadio(self.dlg.R5))
        self.dlg.R6.toggled.connect(lambda:self.WriteFromRadio(self.dlg.R6))
 
     

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            self.runCode()
            
